# Generated by Django 3.1.1 on 2020-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useful_link',
            options={'verbose_name': 'Полезные ссылки', 'verbose_name_plural': 'Полезные ссылки'},
        ),
        migrations.AlterField(
            model_name='useful_link',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
