# Generated by Django 3.1.1 on 2020-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_time',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='Забронировано'),
        ),
        migrations.AlterField(
            model_name='record_time',
            name='name',
            field=models.TextField(max_length=150, verbose_name='Имя клиента'),
        ),
    ]
